### ISSUE TITLE
Time without segment enhancement

### ISSUE THREAD

**Issue by notDevagya** [YTVanced/Integrations#64]
I think this should be a feature of vanced itself, and the time in brackets should be called "effective time" and should also take into account the playback speed as well. 

For example: lets say you are watching a 5 hr video at 2x speed, the time in the brackets =  (5hr - skipped time) / 2

What do you think?

**Comment by caneleex** [comment]
if you have a 5 hour long video and you watch it 2x speed, it's still a 5 hour long video. you just watch it 2 times faster.
