### ISSUE TITLE
RYD on 16.49.37

### ISSUE THREAD

**Issue by Sam101011** [YTVanced/Integrations#71]
I successfully downloaded the newest beta through the Vanced manager to see if the RYD is working, but for me it isn't. A guy in the subreddit had it working, but it also stopped for him. Also the layout is different. 
I know it's still in development and I appreciate you guys doing that, I just want to know if it's something on your end or it's something on ours.
 Thank you!
![Screenshot_20220130_144907](https://user-images.githubusercontent.com/90930406/151700360-0ae55623-a7c1-4959-b2df-5fee55ea5852.jpg)

![Screenshot_20220130_145019](https://user-images.githubusercontent.com/90930406/151700407-54795080-6c14-460c-a7a4-2736b1694c01.jpg)

**Comment by VancedOfficial** [comment]
The correct place for issue reports in Beta are in the beta Discord/Telegram channels.
