### ISSUE TITLE
Bug In SponsorBlock

### ISSUE THREAD

**Issue by Zusyaku** [YTVanced/Integrations#72]
Device: OPPO F1 PLUS
Android Version : 6
Vanced Version: 17.03.38

Sponsorblock cannot view How Many Time I Skipp
![Screenshot_2022-02-17-07-44-06-65](https://user-images.githubusercontent.com/71582475/154382333-b464570a-5899-437d-9e95-f91728a99262.png)

**Comment by caneleex** [comment]
works just fine for me, even with Indonesian set as the language. it was probably a server hiccup, or slow connection.
